const PALETTE = Object.freeze({
  HAXBALL_YELLOW: 0xFFDB72,
  SKY_BLUE: 0xADD8E6,
  LIGHT_GREY: 0xDDDDDD,
  BRIGHT_RED: 0xFF4444,
  BRIGHT_GREEN: 0x00FF00,
  CYAN: 0x00D4FF,
});

export const COLORS = Object.freeze({
  SERVER: PALETTE.HAXBALL_YELLOW,
  DM: PALETTE.SKY_BLUE,
  ERROR: PALETTE.BRIGHT_RED,
  SUCCESS: PALETTE.BRIGHT_GREEN,
  INFO: PALETTE.LIGHT_GREY,
  ADMIN: PALETTE.CYAN,
});
